ammo_man_one addaction [("<t color=""#00008b"">" + ("Diver Medic") + "</t>"), {
comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "U_B_Wetsuit";
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_morphine";
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {player addItemToUniform "20Rnd_556x45_UW_mag";};
player addItemToUniform "30Rnd_556x45_Stanag";
player addVest "V_RebreatherB";
player addBackpack "O_mas_Bergen_blk";
player addItemToBackpack "BWA3_optic_EOTech_Mag_Off";
player addItemToBackpack "ffaa_optic_acog";
player addItemToBackpack "V_PlateCarrier1_blk";
player addItemToBackpack "G_mas_wpn_wrap_c";
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 3 do {player addItemToBackpack "ACE_personalAidKit";};
player addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_atropine";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
player addItemToBackpack "hgun_mas_acp_F";
player addItemToBackpack "arifle_SPAR_01_blk_F";
player addItemToBackpack "Binocular";
for "_i" from 1 to 2 do {player addItemToBackpack "12Rnd_mas_45acp_Mag";};
for "_i" from 1 to 6 do {player addItemToBackpack "30Rnd_556x45_Stanag";};
player addItemToBackpack "30Rnd_556x45_Stanag_red";
player addItemToBackpack "SmokeShellGreen";
player addItemToBackpack "SmokeShellRed";
for "_i" from 1 to 4 do {player addItemToBackpack "SmokeShell";};
player addItemToBackpack "ACE_M84";
player addItemToBackpack "HandGrenade";
player addGoggles "G_B_Diving";

comment "Add weapons";
player addWeapon "arifle_SDAR_F";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemGPS";
}];