private _unit = _this select 0;
comment "Exported from Arsenal by [CC] Mr. Sinn";

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add containers";
_unit forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 3 do {_unit addItemToUniform "30Rnd_556x45_Stanag";};
_unit addVest "V_PlateCarrierIA1_dgtl";
for "_i" from 1 to 4 do {_unit addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 4 do {_unit addItemToVest "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_quikclot";};
_unit addItemToVest "ACE_EarPlugs";
_unit addItemToVest "ACE_EntrenchingTool";
_unit addItemToVest "ACE_packingBandage";
_unit addItemToVest "ACE_morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_tourniquet";};
_unit addItemToVest "ACE_DefusalKit";
for "_i" from 1 to 6 do {_unit addItemToVest "1Rnd_HE_Grenade_shell";};
_unit addItemToVest "1Rnd_SmokeGreen_Grenade_shell";
_unit addItemToVest "1Rnd_SmokeRed_Grenade_shell";
for "_i" from 1 to 2 do {_unit addItemToVest "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 4 do {_unit addItemToVest "SmokeShell";};
_unit addBackpack "B_AssaultPack_rgr";
_unit addItemToBackpack "APERSTripMine_Wire_Mag";
_unit addItemToBackpack "SLAMDirectionalMine_Wire_Mag";
_unit addItemToBackpack "ClaymoreDirectionalMine_Remote_Mag";
_unit addItemToBackpack "ACE_M84";
for "_i" from 1 to 2 do {_unit addItemToBackpack "MiniGrenade";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "HandGrenade";};
_unit addHeadgear "H_HelmetB_light_black";
_unit addGoggles "G_Balaclava_TI_blk_F";

comment "Add weapons";
_unit addWeapon "arifle_SPAR_01_GL_blk_F";
_unit addPrimaryWeaponItem "optic_Aco";
_unit addWeapon "ACE_VMM3";
_unit addWeapon "Binocular";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
