private _unit = _this select 0;
removeAllWeapons _unit;
removeAllItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add containers";
_unit forceAddUniform "U_mas_mar_B_CombatUniform_veg";
_unit addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {_unit addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 4 do {_unit addItemToUniform "ACE_CableTie";};
_unit addItemToUniform "ACE_EntrenchingTool";
_unit addItemToUniform "ACE_Flashlight_MX991";
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_morphine";
for "_i" from 1 to 4 do {_unit addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addItemToUniform "20Rnd_762x51_Mag";
_unit addVest "V_mas_mar_PlateCarrierGL_rgr_g";
_unit addItemToVest "SmokeShellGreen";
_unit addItemToVest "SmokeShellRed";
for "_i" from 1 to 4 do {_unit addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_M84";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToVest "12Rnd_mas_45acp_Mag";};
_unit addItemToVest "B_IR_Grenade";
for "_i" from 1 to 5 do {_unit addItemToVest "20Rnd_762x51_Mag";};
_unit addBackpack "B_AssaultPack_rgr";
_unit addItemToBackpack "ACE_NVG_Gen4";
_unit addItemToBackpack "H_mas_mar_off_v";
_unit addItemToBackpack "acc_pointer_IR";
_unit addItemToBackpack "muzzle_mas_snds_L";
_unit addItemToBackpack "acc_mas_flash_gun";
_unit addItemToBackpack "ACE_IR_Strobe_Item";
_unit addItemToBackpack "ACE_RangeTable_82mm";
_unit addItemToBackpack "ACE_ATragMX";
_unit addItemToBackpack "ACE_DAGR";
_unit addItemToBackpack "ACE_RangeCard";
_unit addItemToBackpack "hlc_muzzle_snds_fal";
for "_i" from 1 to 4 do {_unit addItemToBackpack "Chemlight_green";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "Chemlight_red";};
_unit addHeadgear "H_mas_mar_helmet_ops_sf_v";
_unit addGoggles "G_mas_wpn_gog";

comment "Add weapons";
_unit addWeapon "srifle_EBR_F";
_unit addPrimaryWeaponItem "optic_DMS";
_unit addPrimaryWeaponItem "bipod_01_F_blk";
_unit addWeapon "hgun_mas_acp_F";
_unit addWeapon "Rangefinder";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";