private _unit = _this select 0;
comment "Exported from Arsenal by [CC] Mr. Sinn";

comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "U_B_CTRG_Soldier_F";
player addVest "V_PlateCarrierIA1_dgtl";
for "_i" from 1 to 4 do {player addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 4 do {player addItemToVest "ACE_elasticBandage";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_quikclot";};
player addItemToVest "ACE_EarPlugs";
player addItemToVest "ACE_packingBandage";
player addItemToVest "ACE_morphine";
for "_i" from 1 to 2 do {player addItemToVest "ACE_tourniquet";};
player addItemToVest "ACE_RangeTable_82mm";
player addItemToVest "ACE_ATragMX";
player addItemToVest "ACE_Kestrel4500";
for "_i" from 1 to 6 do {player addItemToVest "1Rnd_HE_Grenade_shell";};
player addItemToVest "1Rnd_SmokeGreen_Grenade_shell";
player addItemToVest "1Rnd_SmokeRed_Grenade_shell";
for "_i" from 1 to 2 do {player addItemToVest "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 4 do {player addItemToVest "20Rnd_762x51_Mag";};
for "_i" from 1 to 2 do {player addItemToVest "9Rnd_45ACP_Mag";};
player addBackpack "B_AssaultPack_rgr";
player addItemToBackpack "ACE_Tripod";
for "_i" from 1 to 2 do {player addItemToBackpack "MiniGrenade";};
player addItemToBackpack "HandGrenade";
for "_i" from 1 to 4 do {player addItemToBackpack "SmokeShell";};
player addHeadgear "H_HelmetB_light_black";
player addGoggles "G_Balaclava_TI_blk_F";

comment "Add weapons";
player addWeapon "arifle_SPAR_03_blk_F";
player addPrimaryWeaponItem "optic_KHS_old";
player addPrimaryWeaponItem "bipod_01_F_blk";
player addWeapon "hgun_ACPC2_F";
player addWeapon "ACE_VectorDay";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";